#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Bicep snapshot tests for infra/main.bicep. No test framework required.

.DESCRIPTION
    Validates that the Bicep template produces the expected set of Azure resources
    with the correct configuration. Loads the snapshot from
    infra/tests/snapshots/main.snapshot.json (generated by the VS Code Bicep
    extension's "Get Deployment Snapshot" command).

    Exit code:
      0 — all assertions passed
      1 — one or more assertions failed

.EXAMPLE
    .\infra\tests\Test-BicepSnapshot.ps1

.NOTES
    To regenerate the snapshot:
      Open infra/main.test.bicepparam in VS Code and invoke
      Bicep: Get Deployment Snapshot. Save the output to
      infra/tests/snapshots/main.snapshot.json.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Load snapshot ─────────────────────────────────────────────────────────────

$snapshotPath = Join-Path $PSScriptRoot 'snapshots/main.snapshot.json'
if (-not (Test-Path $snapshotPath)) {
    Write-Error "Snapshot not found: $snapshotPath`nRun 'Bicep: Get Deployment Snapshot' in VS Code and save to that path."
    exit 1
}

$snapshot  = Get-Content $snapshotPath -Raw | ConvertFrom-Json
$resources = $snapshot.predictedResources

# ── Helpers ───────────────────────────────────────────────────────────────────

$passed = 0
$failed = 0

function Assert([bool]$condition, [string]$name, [string]$detail = '') {
    if ($condition) {
        Write-Host "  [PASS] $name" -ForegroundColor Green
        $script:passed++
    } else {
        $msg = if ($detail) { "$name — $detail" } else { $name }
        Write-Host "  [FAIL] $msg" -ForegroundColor Red
        $script:failed++
    }
}

function Get-ResourcesByType([string]$type) {
    $resources | Where-Object { $_.type -ieq $type }
}

# ── Tests ─────────────────────────────────────────────────────────────────────

Write-Host "`nBicep snapshot — $($resources.Count) resources loaded from: $snapshotPath`n"

# 1. Resource inventory
Write-Host 'Resource inventory' -ForegroundColor Cyan

Assert ($resources.Count -eq 14) `
    'Total resource count is 14'

Assert ((Get-ResourcesByType 'Microsoft.OperationalInsights/workspaces').Count -eq 1) `
    'Exactly 1 Log Analytics workspace'

Assert ((Get-ResourcesByType 'Microsoft.ManagedIdentity/userAssignedIdentities').Count -eq 1) `
    'Exactly 1 User-Assigned Managed Identity'

Assert ((Get-ResourcesByType 'Microsoft.ContainerRegistry/registries').Count -eq 1) `
    'Exactly 1 Container Registry'

Assert ((Get-ResourcesByType 'Microsoft.DBforPostgreSQL/flexibleServers').Count -eq 1) `
    'Exactly 1 PostgreSQL Flexible Server'

Assert ((Get-ResourcesByType 'Microsoft.KeyVault/vaults').Count -eq 1) `
    'Exactly 1 Key Vault'

Assert ((Get-ResourcesByType 'Microsoft.App/managedEnvironments').Count -eq 1) `
    'Exactly 1 Container Apps Managed Environment'

Assert ((Get-ResourcesByType 'Microsoft.App/containerApps').Count -eq 2) `
    'Exactly 2 Container Apps (backend + frontend)'

Assert ((Get-ResourcesByType 'Microsoft.Authorization/roleAssignments').Count -eq 2) `
    'Exactly 2 role assignments (AcrPull + Key Vault Secrets User)'

# 2. Tags
Write-Host "`nTagging" -ForegroundColor Cyan

$taggedTypes = @(
    'Microsoft.OperationalInsights/workspaces'
    'Microsoft.ManagedIdentity/userAssignedIdentities'
    'Microsoft.ContainerRegistry/registries'
    'Microsoft.DBforPostgreSQL/flexibleServers'
    'Microsoft.KeyVault/vaults'
    'Microsoft.App/managedEnvironments'
    'Microsoft.App/containerApps'
)
foreach ($type in $taggedTypes) {
    $res = Get-ResourcesByType $type | Select-Object -First 1
    Assert ($res.tags.application -eq 'kwintbaseharmony') `
        "application tag set on $type"
}

# 3. Container Registry
Write-Host "`nContainer Registry security" -ForegroundColor Cyan

$acr = Get-ResourcesByType 'Microsoft.ContainerRegistry/registries' | Select-Object -First 1
Assert ($acr.properties.anonymousPullEnabled -ne $true) `
    'ACR anonymous pull is disabled'
Assert ($acr.sku.name -eq 'Basic') `
    'ACR uses Basic SKU'

# 4. Key Vault
Write-Host "`nKey Vault security" -ForegroundColor Cyan

$kv = Get-ResourcesByType 'Microsoft.KeyVault/vaults' | Select-Object -First 1
Assert ($kv.properties.enablePurgeProtection -eq $true) `
    'Key Vault purge protection enabled'
Assert ($kv.properties.enableRbacAuthorization -eq $true) `
    'Key Vault uses RBAC (not access policies)'

# 5. PostgreSQL
Write-Host "`nPostgreSQL" -ForegroundColor Cyan

$pg = Get-ResourcesByType 'Microsoft.DBforPostgreSQL/flexibleServers' | Select-Object -First 1
Assert ($pg.properties.highAvailability.mode -eq 'Disabled') `
    'PostgreSQL high availability disabled (Burstable tier)'
Assert ($pg.properties.backup.backupRetentionDays -ge 7) `
    'PostgreSQL backup retention >= 7 days'

# 6. Container Apps ingress
Write-Host "`nContainer Apps ingress" -ForegroundColor Cyan

$apps = Get-ResourcesByType 'Microsoft.App/containerApps'
foreach ($app in $apps) {
    $ingress = $app.properties.configuration.ingress
    Assert ($ingress.external -eq $true) `
        "$($app.name): external ingress enabled"
    Assert ($ingress.targetPort -eq 8080) `
        "$($app.name): ingress target port is 8080"
    Assert ($ingress.allowInsecure -ne $true) `
        "$($app.name): insecure (HTTP) traffic not allowed"
}

# 7. Container Apps scaling
Write-Host "`nContainer Apps scaling" -ForegroundColor Cyan

$backend = $apps | Where-Object { $_.name -match 'api' } | Select-Object -First 1
Assert ($backend.properties.template.scale.minReplicas -ge 1) `
    'Backend minReplicas >= 1'
Assert ($backend.properties.template.scale.maxReplicas -le 10) `
    'Backend maxReplicas <= 10'

$frontend = $apps | Where-Object { $_.name -match 'frontend' } | Select-Object -First 1
Assert ($frontend.properties.template.scale.maxReplicas -le 3) `
    'Frontend maxReplicas <= 3 (cost-aware)'

# 8. Dapr
Write-Host "`nDapr" -ForegroundColor Cyan

Assert ($backend.properties.configuration.dapr.enabled -eq $true) `
    'Backend Dapr sidecar enabled'
Assert ($backend.properties.configuration.dapr.appId -eq 'kwintbaseharmony-api') `
    'Backend Dapr appId is kwintbaseharmony-api'
Assert ($frontend.properties.configuration.dapr.enabled -eq $true) `
    'Frontend Dapr sidecar enabled'
Assert ($frontend.properties.configuration.dapr.appId -eq 'kwintbaseharmony-frontend') `
    'Frontend Dapr appId is kwintbaseharmony-frontend'

# ── Summary ───────────────────────────────────────────────────────────────────

Write-Host "`n─────────────────────────────────────────"
Write-Host "Passed: $passed   Failed: $failed" -ForegroundColor $(if ($failed -gt 0) { 'Red' } else { 'Green' })

if ($failed -gt 0) {
    Write-Host "FAILED — $failed assertion(s) did not pass." -ForegroundColor Red
    exit 1
}

Write-Host "All assertions passed." -ForegroundColor Green
exit 0
