apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgresdb
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=localhost port=5432 dbname=kwintbaseharmony user=postgres password=postgres sslmode=disable"
