// <auto-generated />
using System;
using KwintBaseHarmony.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KwintBaseHarmony.Migrations
{
    [DbContext(typeof(CompositionContext))]
    [Migration("20260417000000_AddMovements")]
    partial class AddMovements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");

            modelBuilder.Entity("KwintBaseHarmony.Models.Composition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CompletionPercentage")
                        .HasPrecision(5, 1)
                        .HasColumnType("numeric(5,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("MovementNumber")
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("ParentCompositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("RootMidi")
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasName("IX_Compositions_CreatedAt");

                    b.HasIndex("ParentCompositionId")
                        .HasName("IX_Compositions_ParentCompositionId");

                    b.HasIndex("StudentId")
                        .HasName("IX_Compositions_StudentId");

                    b.ToTable("Compositions");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Layer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Concept")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LayerNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PuzzleAnswersJson")
                        .HasColumnType("text");

                    b.Property<long>("TimeSpentMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CompositionId", "LayerNumber")
                        .IsUnique()
                        .HasName("IX_Layers_CompositionId_LayerNumber");

                    b.ToTable("Layers");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Pitch")
                        .HasColumnType("integer");

                    b.Property<int>("TimingMs")
                        .HasColumnType("integer");

                    b.Property<int>("Velocity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("LayerId")
                        .HasName("IX_Notes_LayerId");

                    b.HasIndex("LayerId", "TimingMs")
                        .HasName("IX_Notes_LayerId_TimingMs");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Composition", b =>
                {
                    b.HasOne("KwintBaseHarmony.Models.Composition", "ParentComposition")
                        .WithMany()
                        .HasForeignKey("ParentCompositionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentComposition");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Layer", b =>
                {
                    b.HasOne("KwintBaseHarmony.Models.Composition", "Composition")
                        .WithMany("Layers")
                        .HasForeignKey("CompositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Composition");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Note", b =>
                {
                    b.HasOne("KwintBaseHarmony.Models.Layer", "Layer")
                        .WithMany("Notes")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Composition", b =>
                {
                    b.Navigation("Layers");
                });

            modelBuilder.Entity("KwintBaseHarmony.Models.Layer", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
